In [5]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("../data/master/studytime2.csv")
df["day of week"] = pd.Categorical(df["day of week"], categories=["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"], ordered=True)

In [7]:
df

,term,week,day of week,course,duration,start_date,end_date,due_date,title
0,fa23,5,Monday,MATH 241,60,2023-09-18 19:30:00,2023-09-18 20:30:00,2023-09-20,HW8
1,fa23,5,Tuesday,PHYS 213/214,15,2023-09-19 19:30:00,2023-09-19 19:45:00,2023-09-19,pre lecture 10
2,fa23,5,Wednesday,STAT 107,15,2023-09-20 10:00:00,2023-09-20 10:15:00,2023-09-20,HW11
3,fa23,5,Thursday,MATH 241,60,2023-09-21 13:50:00,2023-09-21 14:50:00,NaN,Work on Calc Review Packet
4,fa23,5,Thursday,PHYS 213/214,30,2023-09-21 15:00:00,2023-09-21 15:30:00,2023-09-25,HW9
...,...,...,...,...,...,...,...,...,...
877,sp25,3,Sunday,Research,120,2025-02-09 09:00:00,2025-02-09 11:00:00,NaN,NaN
878,sp25,3,Sunday,ASTR 405,120,2025-02-09 14:30:00,2025-02-09 16:30:00,NaN,Weekly Review
879,sp25,3,Sunday,CHEM 104/105,15,2025-02-09 16:30:00,2025-02-09 16:45:00,2025-02-11,Quiz 1
880,sp25,3,Sunday,CHEM 104/105,15,2025-02-09 16:45:00,2025-02-09 17:00:00,2025-02-10,HW&PL
881,sp25,3,Sunday,GEOL 432,30,2025-02-09 17:00:00,2025-02-09 17:30:00,2025-02-10,Quiz Study

In [ ]:
df2 = df[df['term'] == 'sp24'].groupby(['day of week', 'course', 'term']).agg('mean').reset_index()[['day of week', 'course', 'duration']]
sns.barplot(df2, x='day of week', y='duration')

/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_3103/190276188.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df2 = df[df['term'] == 'sp24'].drop('title',axis=1).groupby(['day of week', 'course', 'term']).agg('mean').reset_index()[['day of week', 'course', 'duration']]

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
df[df['term'] == 'fa24'][['week', 'day of week', 'duration']].groupby(["day of week", "week"]).agg('sum').reset_index()[['day of week', 'duration']].groupby('day of week').agg('mean')

/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_7156/739961838.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[df['term'] == 'fa24'][['week', 'day of week', 'time spent (min)']].groupby(["day of week", "week"]).agg('sum').reset_index()[['day of week', 'time spent (min)']].groupby('day of week').agg('mean')
/var/folders/41/_gkgvhb94wd4156zplzr4cg00000gn/T/ipykernel_7156/739961838.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[df['term'] == 'fa24'][['week', 'day of week', 'time spent (min)']].groupby(["day of week", "week"]).agg('sum').reset_index()[['day of week', 'time spent (min)']].groupby('day of week').agg('mean')

             time spent (min)
day of week
Sunday             153.333333
Monday             107.916667
Tuesday            113.750000
Wednesday          130.000000
Thursday            63.750000
Friday              27.500000
Saturday            85.000000

In [17]:
df[df['term'] == 'sp25'][['week', 'duration']].groupby(['week']).agg('sum') / 60

       duration
week
1     16.766667
2     27.000000
3     28.750000

In [18]:
df[df['term'] == 'sp25'][['week', 'course', 'duration']].groupby(['week', 'course']).agg('sum') / 60

                    duration
week course
1    ASTR 405       1.000000
     CHEM 104/105   2.516667
     CS 307         0.750000
     Research      12.500000
2    ASTR 405       6.250000
     CHEM 104/105   3.250000
     CS 307         0.250000
     GEOL 432       8.250000
     Research       9.000000
3    ASTR 405       5.500000
     CHEM 104/105   1.750000
     CS 307         2.500000
     GEOL 432      11.250000
     Research       7.750000